### ISSUE TITLE
Merge security related PRs

### ISSUE THREAD

**Issue by Somebodyisnobody** [mrsimpson/ical-interceptor#19]
Hi,
I use the ical interceptor and updated the dependencies which are still open here. There are a few security patches. @mrsimpson can you merge at least the security-related ones so that others are save?

**Comment by mrsimpson** [comment]
Oh wow, somebody except myself is using it? Awesome ;-)
I should find some time those days to update the dependencies, I might also set up renotave or dependabot. Might 😬

**Comment by mrsimpson** [comment]
I actually only noticed I even had automated tests in place. The dependencies we're looking undangerous, so I just merged them after successful automated test on my phone. 
What a crazy world...

**Comment by Somebodyisnobody** [comment]
Thank you very much. Yeah our use case is a typo3-calendar. Here the backend offers an ics-file ([example](https://ov-bonn.thw.de/unser-ortsverband/terminkalender/kalender/ics/?type=150&tx_cal_controller%5Bcalendar%5D=289)) but without reminder. As far as I know typo3 doesn't support generating an ics-file dynamically by the user. With your tool everyone can set his own reminder with your tool. 👍

**Comment by mrsimpson** [comment]
Awesome!
Pipeline failed, thus reopening it. Let's see to it later the day. Or week. Or month
