### ISSUE TITLE
Return response in mimetype text/plain or as download

### ISSUE THREAD

**Issue by Somebodyisnobody** [mrsimpson/ical-interceptor#20]
I suggest to return the response with the modified calendar events as mimetype `text/plain` instead of default `text/html`. This would break the text with a new line where it should be breaked.
It would be also an idea to offer the new icalendar as download via following http headers:
```
Content-Type: application/octet-stream
Content-Disposition: attachment;filename=\"<inputfilename + "intercepted">.ics\"
```
entry point:
https://github.com/mrsimpson/ical-interceptor/blob/ea9033423fc6b3517a772e72a6db12fd12e3795b/handler.js#L32-L34

Both solutions are okay for me. Could this break something on the user edge?

**Comment by mrsimpson** [comment]
Nope, I don't think it will break something moving to text/html.
I'll probably offer a parameter to request an explicit download

**Comment by Somebodyisnobody** [comment]
You mean from html right?

**Comment by mrsimpson** [comment]
`text/plain` is now default response mime type.
If you supply `&download`, it will return it as `application/octet-stream`

**Comment by Somebodyisnobody** [comment]
That sounds nice! Thank you
