### ISSUE TITLE
Accept url=webcal://...

### ISSUE THREAD

**Issue by Somebodyisnobody** [mrsimpson/ical-interceptor#24]
Hello,
currently I'm writing a tutorial for mere mortals on how to build their own calendar subscription with reminders. In doing so, I'm having some difficulty explaining that they should copy the webcal://foo.bar/foobar.ics link without reminders then replace the "webcal" with an "https" and then paste the string into `webcal://mrsimpson.o6s.io/ical-interceptor?url=`. IIs it possible to support webcal:// links in the `url` parameter?

**Comment by Somebodyisnobody** [comment]
https://github.com/mrsimpson/ical-interceptor/blob/f0870e9c743e344a81f77e1afd2c239cc5110b20/src/readJcalFromUrl.js#L4-L19

Here we in line 6 need a
```js
if (url.startsWith('webcal')) url = 'http' + url.substring(6);
```

**Comment by mrsimpson** [comment]
Hmmm – not quite sure whether it's always http**s**.

**Comment by Somebodyisnobody** [comment]
I heard about webcals:// for TLS-requests but it's not documented in the RFC. For compatiblity i'ld say that http is good. Of course we could still say first try to get via https if it throws an error then via http. How does the service react on 301 or 302 redirects?

**Comment by mrsimpson** [comment]
I decided to be more aggressive ;)
It's probably the two of us using this tool, so why not optimize for the audience...

**Comment by Somebodyisnobody** [comment]
Looks good! Thank you.
